import type { ForceAbility, LightsaberForm, NightSisterSpell } from './types'

export const forceAbilities: ForceAbility[] = [
  {
    name: 'Telekinesis',
    access: ['Youngling', 'Acolyte', 'Sith Alchemist'],
    description: 'Move objects with the power of your mind. Make a Force check to lift and hurl objects at targets or manipulate the environment at range.',
    range: '25ft',
    higherRank: 'Range increases to 30ft at rank 2, 35ft at rank 3, 40ft at rank 4, and 50ft at rank 5.',
    cooldown: 'N/A',
  },
  {
    name: 'Force Speed',
    access: ['Youngling', 'Acolyte'],
    description: 'Bonus Action: Channel the Force to double your movement speed for the turn. Using this ability more than once per short rest deals 1d4 damage to yourself.',
    range: 'Self',
    higherRank: 'Rank 2 allows 2 uses without consequence; rank 3 allows 3 uses without consequence.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Force Jump',
    access: ['Youngling', 'Acolyte'],
    description: 'Bonus Action: Leap up to 20ft vertically using the Force. Using this ability more than once per short rest deals 1d4 damage to yourself.',
    range: 'Self',
    higherRank: 'Rank 2 allows 2 uses without consequence; rank 3 allows 3 uses without consequence.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Force Sense',
    access: ['Padawan I', 'Apprentice I'],
    description: 'Action: Extend your Force presence outward to detect the location and emotional state of other living beings within range.',
    range: '25ft',
    higherRank: 'Range increases to 35ft at rank 2, 50ft at rank 3, and 65ft at rank 4.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Detoxify Poison',
    access: ['Padawan II'],
    description: 'Action: Channel the Force through a creature to neutralize and break down poisons and toxins affecting their body.',
    range: '5ft',
    higherRank: 'N/A',
    cooldown: 'Short Rest',
  },
  {
    name: 'Bleeding',
    access: ['Apprentice II', 'Codebreaker III'],
    description: 'Action: Pour your pain and anger into a kyber crystal, causing it to bleed. A Force check result of DC 13 or higher produces a red crystal; 10–12 produces a purple crystal.',
    range: 'Self',
    higherRank: 'N/A',
    cooldown: 'Short Rest',
  },
  {
    name: 'Cleanse Mind',
    access: ['Knight I', 'Diplomat I', 'Sentinel I', 'Hermit I'],
    description: 'Action: Purge mind-altering effects from yourself or an ally. Make a Force check against DC 15 to successfully cleanse the affliction.',
    range: '5ft',
    higherRank: 'DC reduces to 13 at rank 2, and 11 at rank 3.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Battle Meditation',
    access: ['Knight I', 'Diplomat I', 'Sentinel I', 'Hermit I', 'Code Breaker I'],
    description: 'Action: Enter a meditative state mid-combat that enhances your connection to the Force, granting +2 to Force and Athletics checks. While active you cannot take bonus actions.',
    range: 'Self',
    higherRank: 'Bonus increases to +4 at rank 2.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Hatred',
    access: ['Sith I', 'Vengeful I', 'Duelist I', 'Assassin I', 'Conflicted I', 'Apostate II'],
    description: 'Action: Fuel your power with hatred and anger, gaining +2 to Force checks and advantage on Strength-based attack rolls.',
    range: 'Self',
    higherRank: 'Rank 2 increases the bonus to +4 and grants advantage on all attack rolls.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Choke',
    access: ['Sith I', 'Vengeful I', 'Duelist II', 'Assassin I', 'Conflicted I', 'Apostate III'],
    description: 'Action: Compress a target\'s windpipe with the Force. The target must make a Constitution saving throw (DC 12) each turn or take 1d6 damage and suffer disadvantage on attack rolls.',
    range: '15ft',
    higherRank: 'DC increases to 14 at rank 2, and 16 at rank 3.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Mind Trick',
    access: ['Knight II', 'Diplomat II', 'Sentinel II', 'Hermit II'],
    description: 'Action: Bend a weak-minded target to your will. Target makes an Intelligence saving throw (DC 13 out of combat, DC 10 in combat) or follows a simple command.',
    range: '5ft',
    higherRank: 'DC increases to 14 at rank 2, and 15 at rank 3.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Force Lightning',
    access: ['Lord I', 'Hateful I', 'Count I'],
    description: 'Action: Unleash crackling dark-side energy from your fingertips, dealing 3d8 lightning damage. Target must make a Constitution saving throw (DC 15) or be stunned until end of next turn.',
    range: '20ft',
    higherRank: 'DC increases to 17 at rank 2.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Stasis',
    access: ['Knight III', 'Sentinel III', 'Hermit III', 'Diplomat III', 'Negotiator II', 'Vanguard III'],
    description: 'Reaction: Halt an incoming projectile or attack in mid-air (Force check DC 15). On success you may hurl it back at the attacker; the attacker makes a Dexterity saving throw (DC 12) or is struck by their own projectile.',
    range: '30ft',
    higherRank: 'N/A',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Stun',
    access: ['Master III', 'Negotiator III', 'Silent Fist III', 'Vanguard III', 'Apostate IV'],
    description: 'Action: Overwhelm a target\'s nervous system with Force energy. Target makes a Dexterity saving throw (DC 12) or is stunned while you maintain concentration.',
    range: '25ft',
    higherRank: 'N/A',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Healing',
    access: ['Silent Fist', 'Sage'],
    description: 'Action: Channel life-giving Force energy into a wounded creature. Make a Force check — the result determines the healing die rolled: low rolls heal 1d6, moderate 1d8, high 1d10, exceptional 1d12.',
    range: '10ft',
    higherRank: 'N/A',
    cooldown: '2x per Long Rest',
  },
  {
    name: 'Force Shield',
    access: ['Sentinel II'],
    description: 'Action: Erect a shimmering barrier of Force energy around a target. Make a Force check (DC 12) to grant the target 1d8 temporary hit points.',
    range: '30ft',
    higherRank: 'Rank 2 grants 2d8 temporary hit points; rank 3 grants 3d6.',
    cooldown: '2x per Long Rest',
  },
  {
    name: 'Force Barrier',
    access: ['Vanguard II'],
    description: 'Reaction: Throw up a Force barrier to absorb an incoming attack. Make a Force check (DC 14) to nullify the damage entirely; on a failure the damage is halved.',
    range: '20ft',
    higherRank: 'DC reduces to 12 at rank 2.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Projection',
    access: ['Grandmaster', 'One with the Force'],
    description: 'Action: Project a perfect Force-generated copy of yourself to a distant location. Make a Force check (DC 17) to maintain the illusion while concentrating. The copy can speak and interact but cannot physically affect the world.',
    range: 'Unlimited',
    higherRank: 'N/A',
    cooldown: 'Long Rest',
  },
  {
    name: 'Precognition',
    access: ['Master I', 'Negotiator I', 'Silent Fist I', 'Vanguard I', 'Apostate I'],
    description: 'Passive: Through your deep bond with the Force you instinctively feel when terrible things befall beings you are emotionally connected to, regardless of distance.',
    range: 'Galaxy',
    higherRank: 'N/A',
    cooldown: 'N/A',
  },
  {
    name: 'Force Light',
    access: ['Master I', 'Negotiator I', 'Vanguard I'],
    description: 'Action: Flood an area with blinding light-side energy, purifying dark-side corruption. Make a Force check (DC 17); evil-aligned creatures within range suffer disadvantage on all rolls while you maintain concentration.',
    range: '45ft',
    higherRank: 'Range increases to 60ft at rank 2.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Drain',
    access: ['Darth (Sith)'],
    description: 'Action: Siphon the life force from a target. Target makes a Force check (DC 12) then a Constitution save (DC 14); on failure takes 1d10 damage which heals you for the same amount.',
    range: '10ft',
    higherRank: 'N/A',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Maelstrom',
    access: ['All Darth', 'Grand Inquisitor', 'Fallen'],
    description: 'Action: Unleash a catastrophic storm of Force energy that strikes all creatures in range. All creatures make a Strength save (DC 18) or take 5d8 damage. You also suffer 2d8 damage from the strain. Requires concentration.',
    range: '40ft',
    higherRank: 'N/A',
    cooldown: 'Long Rest',
  },
  {
    name: 'Transfer Essence',
    access: ['All Darth'],
    description: 'Action: Attempt to transfer your consciousness into another body. Target makes a Force save (DC 18) and then a Strength save (DC 12) or their mind is displaced and you inhabit their body.',
    range: '5ft',
    higherRank: 'N/A',
    cooldown: 'Once per Campaign Arc',
  },
  {
    name: 'Force Walk',
    access: ['All Darth', 'Fallen'],
    description: 'Action: Tear a Sith Force ghost into yourself, absorbing its power. Roll a d20 against the ghost\'s DC; failure deals 5d12 damage to you. Success grants immense power while you concentrate.',
    range: 'Self',
    higherRank: 'N/A',
    cooldown: 'Once per Campaign',
  },
  {
    name: 'Animal Bond',
    access: ['Padawan II', 'Hermit II', 'Tribesman II'],
    description: 'Action: Forge a Force-enhanced bond with a willing animal, allowing you to sense its emotions, communicate simple concepts, and issue commands it will endeavor to follow.',
    range: '10ft',
    higherRank: 'Higher ranks deepen the bond, allowing more complex commands and longer range communication.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Judgement',
    access: ['Knight II', 'Negotiator II', 'Sage II'],
    description: 'Action: Channel righteous Force energy to smite a target. On a successful Force check, deal additional radiant damage on your next attack equal to your Force modifier.',
    range: 'Self',
    higherRank: 'Higher ranks increase the bonus damage die.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Flashburn',
    access: ['Sentinel II', 'Assassin II'],
    description: 'Action: Emit an intense burst of Force-amplified light that temporarily blinds targets in a small area. Affected creatures make a Dexterity save or are blinded until the end of their next turn.',
    range: '15ft',
    higherRank: 'Higher ranks extend the blinded duration.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Revitalize',
    access: ['Sage I', 'Silent Fist II'],
    description: 'Action: Flood a downed ally with Force energy, bringing them back from unconsciousness and restoring a small number of hit points.',
    range: '5ft',
    higherRank: 'Higher ranks restore more hit points on revival.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Truth Sense',
    access: ['Knight I', 'Negotiator I', 'Diplomat II'],
    description: 'Passive: Your attunement to the Force allows you to sense deception. When a creature speaks to you directly, you may make a Force check to detect if they are being deliberately dishonest.',
    range: '10ft',
    higherRank: 'Higher ranks lower the DC required to detect deception.',
    cooldown: 'N/A',
  },
  {
    name: 'Morichro',
    access: ['Sage III', 'Hermit III'],
    description: 'Action: Use the Force to dramatically slow a target\'s metabolic functions, rendering them deeply unconscious and greatly slowing their healing. Requires concentration.',
    range: '10ft',
    higherRank: 'Higher ranks allow the technique to be maintained without concentration.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Plant Surge',
    access: ['Hermit II', 'Tribesman II'],
    description: 'Action: Pour Force energy into surrounding plant life, causing rapid and aggressive growth. Plants entangle and restrain targets in the area for as long as you concentrate.',
    range: '30ft',
    higherRank: 'Higher ranks increase the area of effect and entanglement DC.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Sever Force',
    access: ['Master II', 'Grand Inquisitor'],
    description: 'Action: Attempt to permanently sever a Force-sensitive creature\'s connection to the Force. Both parties make opposing Force checks; if you succeed, the target loses Force sensitivity until magically restored.',
    range: '5ft',
    higherRank: 'N/A',
    cooldown: 'Once per Campaign Arc',
  },
  {
    name: 'Life Transfer',
    access: ['Sage III', 'Silent Fist III'],
    description: 'Action: Transfer your own life energy to a critically wounded ally. You spend hit points to heal another creature by the same amount.',
    range: '5ft',
    higherRank: 'Higher ranks improve the transfer ratio.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Echo',
    access: ['Hermit I', 'Sage I', 'Negotiator I'],
    description: 'Action: Touch an object or location and receive a Force-vision of significant past events tied to it. The clarity and depth of the vision depends on a Force check.',
    range: 'Touch',
    higherRank: 'Higher ranks allow you to experience older and more distant echoes.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Force Empathy',
    access: ['Diplomat I', 'Sage I', 'Hermit I'],
    description: 'Passive: You can sense the surface emotions of creatures around you through the Force, gaining insight into their current mental and emotional state without requiring a check.',
    range: '10ft',
    higherRank: 'Higher ranks allow deeper emotional reading and occasionally surface thoughts.',
    cooldown: 'N/A',
  },
  {
    name: 'Corpse Vision',
    access: ['Sith II', 'Apostate II', 'Fallen II'],
    description: 'Action: Reach into the dark-side imprint left by death and experience the final moments of a corpse, seeing through its eyes and hearing what it heard.',
    range: 'Touch',
    higherRank: 'Higher ranks allow you to interact with what you witness, not just observe.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Force Wraith',
    access: ['Darth (Sith)', 'Fallen III'],
    description: 'Action: Summon a dark-side wraith from the Force to terrorize and attack your enemies. The wraith is semi-autonomous and pursues targets you designate while you concentrate.',
    range: '30ft',
    higherRank: 'Higher ranks summon more powerful or numerous wraiths.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Dark Aura',
    access: ['Sith II', 'Hateful I', 'Vengeful II'],
    description: 'Action: Emanate a palpable aura of dark-side dread. Creatures of your choice within range must make a Wisdom save or become frightened of you for 1 minute.',
    range: '20ft',
    higherRank: 'Higher ranks increase the save DC and duration.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Darkshear',
    access: ['Lord II', 'Count II'],
    description: 'Action: Condense dark-side energy into a razor-sharp projectile and hurl it at a target. Make a Force attack roll; on hit the projectile deals 2d8 necrotic damage and ignores most forms of physical armor.',
    range: '30ft',
    higherRank: 'Higher ranks increase the damage die.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Drain Knowledge',
    access: ['Sith III', 'Apostate III', 'Inquisitor II'],
    description: 'Action: Tear information directly from a target\'s mind through the dark side. Target makes an Intelligence save; on failure you extract a specific memory or piece of knowledge of your choice.',
    range: '5ft',
    higherRank: 'Higher ranks lower the save DC.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Destruction',
    access: ['Lord III', 'Darth (Sith)'],
    description: 'Action: Focus an enormous amount of dark-side energy into a single devastating blast. Targets in a line or cone make Dexterity saves or take massive damage. You are exhausted after use.',
    range: '40ft',
    higherRank: 'Higher ranks increase the blast size and damage.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Scream',
    access: ['Vengeful II', 'Hateful II', 'Conflicted II'],
    description: 'Action: Release anguish and rage as a wave of destructive Force energy. All creatures in a cone must make a Constitution save or take thunder damage and be knocked prone.',
    range: '20ft cone',
    higherRank: 'Higher ranks increase the damage and cone size.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Wind',
    access: ['Knight II', 'Vanguard II', 'Tribesman II'],
    description: 'Action: Conjure a powerful gust of Force-amplified wind that pushes creatures and objects. Targets make Strength saves or are knocked back 15ft and fall prone.',
    range: '30ft',
    higherRank: 'Higher ranks increase the push distance and area of effect.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Force Track',
    access: ['Sentinel I', 'Assassin I', 'Hermit I'],
    description: 'Passive: You can sense the Force-imprint left behind by Force-sensitive individuals, allowing you to follow their trail through environments even when physical signs are absent.',
    range: 'N/A',
    higherRank: 'Higher ranks allow tracking of non-Force-sensitives and through shielded environments.',
    cooldown: 'N/A',
  },
  {
    name: 'Force Stealth',
    access: ['Sentinel II', 'Assassin II', 'Silent Fist I'],
    description: 'Action: Suppress your Force presence, making yourself invisible to Force sense and difficult to detect through mundane means. Lasts until you take an aggressive action.',
    range: 'Self',
    higherRank: 'Higher ranks allow you to extend the stealth to nearby allies.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Instinctive Astrogation',
    access: ['Padawan II', 'Youngling (prodigy)', 'Pilot II'],
    description: 'Passive: Through the Force you can intuitively calculate hyperspace routes, reducing astrogation time dramatically and allowing jumps to uncharted coordinates with significantly reduced risk.',
    range: 'N/A',
    higherRank: 'Higher ranks allow near-instant route calculation and jumps through hazardous regions.',
    cooldown: 'N/A',
  },
  {
    name: 'Malacia',
    access: ['Knight III', 'Negotiator II', 'Sage II'],
    description: 'Action: Disrupt a target\'s sense of balance and spatial orientation through the Force. Target makes a Constitution save or is incapacitated with severe vertigo, falling prone and unable to act until the end of their next turn.',
    range: '20ft',
    higherRank: 'Higher ranks extend the effect duration.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Memory Walk',
    access: ['Sith III', 'Inquisitor III', 'Sage III'],
    description: 'Action: Dive deep into a target\'s memories, reliving them as a shared experience. Both you and the target experience the memory together. Target makes a Wisdom save to resist.',
    range: '5ft',
    higherRank: 'Higher ranks allow you to alter small details of the memory during the walk.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Mnemotherapy',
    access: ['Sage II', 'Diplomat III', 'Hermit III'],
    description: 'Action: Gently guide a willing target through their memories using the Force to heal psychological trauma, remove implanted suggestions, or restore suppressed recollections.',
    range: 'Touch',
    higherRank: 'Higher ranks allow treatment of deeper or more severe mental wounds.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Inspire',
    access: ['Knight I', 'Diplomat I', 'Negotiator I', 'Vanguard I'],
    description: 'Action: Channel hope and courage through the Force to bolster your allies. Allies of your choice who can see or hear you gain advantage on their next saving throw or attack roll.',
    range: '30ft',
    higherRank: 'Higher ranks increase the number of allies affected and the duration of the bonus.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Control Web',
    access: ['Sith Alchemist III', 'Lord II'],
    description: 'Action: Extend your Force presence to simultaneously exert telekinetic force on multiple targets or objects at once, creating a web of control within range.',
    range: '30ft',
    higherRank: 'Higher ranks increase the number of targets you can hold simultaneously.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Dark Energy Trap',
    access: ['Sith II', 'Apostate III', 'Lord I'],
    description: 'Action: Lay an invisible dark-side trap at a location. The first creature to enter the trapped square triggers an explosion of dark energy, taking damage and making a Constitution save or being stunned.',
    range: '20ft',
    higherRank: 'Higher ranks allow multiple traps and increased damage.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Crush Opposition',
    access: ['Lord II', 'Darth (Sith)', 'Grand Inquisitor'],
    description: 'Action: Exert an overwhelming Force presence to crush the willpower of all enemies in range. Targets make Wisdom saves or become frightened and cannot move toward you for 1 minute.',
    range: '30ft',
    higherRank: 'Higher ranks increase the area and save DC.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Mechu-Deru',
    access: ['Sith Alchemist II', 'Tinkerer III'],
    description: 'Action: Extend your Force perception into machines and droids, intuitively understanding their function and communicating with them. At higher ranks you can dominate or reprogram droids through the Force.',
    range: '10ft',
    higherRank: 'Higher ranks allow remote control and reprogramming of droids and mechanical systems.',
    cooldown: 'Short Rest',
  },
  {
    name: 'Hibernation Trance',
    access: ['Youngling', 'Acolyte', 'Padawan I', 'Apprentice I'],
    description: 'Action: Enter a deep Force-mediated hibernation, dramatically slowing your metabolism. In this state you need no food, water, or air, your vital signs become nearly undetectable, and you heal at double the normal rate.',
    range: 'Self',
    higherRank: 'Higher ranks reduce the time needed to enter and exit the trance.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Force Absorption',
    access: ['Master II', 'Vanguard III', 'Silent Fist III'],
    description: 'Reaction: Absorb incoming Force-based energy attacks, converting them into Force points or temporary hit points for yourself. Make a Force check against the attack\'s DC to absorb successfully.',
    range: 'Self',
    higherRank: 'Higher ranks allow absorption of non-Force energy attacks as well.',
    cooldown: 'Long Rest',
  },
]

export const lightsaberForms: LightsaberForm[] = [
  {
    name: 'Chii-Sho',
    title: 'Way of the Sarlacc / Determination',
    ranks: [
      {
        rank: 1,
        name: 'Parry Stance',
        description: 'Adopt a wide defensive posture that allows you to parry incoming melee attacks. When a melee attack hits you, you may use your reaction to reduce the damage by 1d6 + your proficiency bonus.',
        cooldown: '1 reaction per turn',
      },
      {
        rank: 2,
        name: 'Body Target Zone',
        description: 'Train your attacks to target vulnerable body zones, bypassing defensive stances. Your melee attacks ignore the benefits of the Parry Stance and similar defensive reactions.',
        cooldown: 'N/A',
      },
      {
        rank: 3,
        name: 'Disarming Slash',
        description: 'Combine a powerful slash with a wrist-twisting maneuver to knock a weapon from your opponent\'s grip. On a hit, target makes a Strength save (DC 13) or is disarmed.',
        cooldown: '2 turns',
      },
      {
        rank: 4,
        name: 'Sarlacc Sweep',
        description: 'Execute a wide spinning sweep of your blade, striking all enemies within 5ft of you. Make a separate attack roll against each adjacent target.',
        cooldown: '3 turns',
      },
      {
        rank: 5,
        name: 'Body Barrage',
        description: 'Unleash a relentless series of powerful strikes against a single target, each blow pushing them back. Deal damage with three attacks; target is pushed 5ft backward after each hit.',
        cooldown: '3 turns',
      },
    ],
  },
  {
    name: 'Makashi',
    title: 'Way of the Ysalamiri / Contention',
    ranks: [
      {
        rank: 1,
        name: 'Power Thrust',
        description: 'Channel your strength into a precise forward thrust aimed at openings in the opponent\'s guard. On a hit, deal an additional 1d6 piercing damage.',
        cooldown: '2 turns',
      },
      {
        rank: 2,
        name: 'Makashi Salute',
        description: 'Open combat with the formal Makashi salute, which subtly analyzes your opponent\'s stance. You gain +2 to attack rolls against this opponent for the first round of combat.',
        cooldown: 'Once per encounter',
      },
      {
        rank: 3,
        name: 'Flourish',
        description: 'Perform an elaborate and distracting blade flourish that forces your opponent to track the blade\'s movement. Target suffers disadvantage on their next attack roll against you.',
        cooldown: '2 turns',
      },
      {
        rank: 4,
        name: 'Contentious Opportunity',
        description: 'Exploit any gap in your opponent\'s offense the moment they overextend. When a creature misses you with a melee attack, make one melee attack against them as a reaction.',
        cooldown: '1 reaction per turn',
      },
      {
        rank: 5,
        name: 'Makashi Riposte',
        description: 'The pinnacle of Makashi technique. When a creature misses you with a melee attack, make a melee attack with advantage and deal an extra 2d6 damage on a hit.',
        cooldown: '1 reaction, 3 turns',
      },
    ],
  },
  {
    name: 'Soresu',
    title: 'Way of the Mynock / Resilience',
    ranks: [
      {
        rank: 1,
        name: 'Block',
        description: 'Use your lightsaber to deflect a ranged attack. When targeted by a ranged weapon attack, use your reaction to add your proficiency bonus to your AC against that attack.',
        cooldown: '1 reaction per turn',
      },
      {
        rank: 2,
        name: 'Resilient Advance',
        description: 'Move forward through incoming fire without breaking your guard. You may move up to half your speed without provoking opportunity attacks and with resistance to ranged weapon damage for that movement.',
        cooldown: '2 turns',
      },
      {
        rank: 3,
        name: 'Mynock Guard',
        description: 'Enter a tight, all-encompassing defensive posture. Until the start of your next turn, all attack rolls against you have disadvantage, but you may not make attacks of opportunity.',
        cooldown: '3 turns',
      },
      {
        rank: 4,
        name: 'Deflecting Slash',
        description: 'Redirect a blocked ranged projectile back at the attacker in the same motion. When you successfully block a ranged attack, you may immediately make a ranged attack with the deflected projectile against any target in range.',
        cooldown: '3 turns',
      },
      {
        rank: 5,
        name: 'Circle of Shelter',
        description: 'Extend your defensive mastery to protect all allies within 5ft of you. Allies adjacent to you also benefit from your Block ability against ranged attacks for the duration of this stance.',
        cooldown: '3 turns, concentration',
      },
    ],
  },
  {
    name: 'Ataru',
    title: 'Way of the Hawk-Bat / Aggression',
    ranks: [
      {
        rank: 1,
        name: 'Offensive Defense',
        description: 'Channel aggression into a reckless offensive stance. Gain +2 to attack rolls but your AC is reduced by 2 until the start of your next turn.',
        cooldown: 'N/A',
      },
      {
        rank: 2,
        name: 'Dark Lunge',
        description: 'Hurl yourself through the air in a Force-propelled lunge, closing distance instantly and striking with the momentum of the leap. Move up to 20ft in a straight line and make an attack with advantage at the end.',
        cooldown: '2 turns',
      },
      {
        rank: 3,
        name: 'Hawk-Bat Swoop',
        description: 'Leap over your opponent\'s defenses and attack from above, ignoring shields and defensive stances. This attack cannot be reduced by reactions and deals an additional 1d8 damage.',
        cooldown: '3 turns',
      },
      {
        rank: 4,
        name: 'Flip Reset',
        description: 'Execute a backflip to escape melee range and immediately reset your position. Disengage without provoking opportunity attacks and land up to 15ft away. You may then make one ranged Force attack as part of the same action.',
        cooldown: '2 turns',
      },
      {
        rank: 5,
        name: 'Saber Swarm',
        description: 'Channel Force speed into your blade technique, delivering a whirlwind of strikes so fast they blur. Make four attacks against one or more targets within melee reach in a single action.',
        cooldown: '3 turns',
      },
    ],
  },
  {
    name: 'Djem So',
    title: 'Way of the Krayt Dragon / Perseverance',
    ranks: [
      {
        rank: 1,
        name: 'Forceful Strike',
        description: 'Put your full body weight behind a strike designed to stagger your opponent. On a hit, the target must make a Strength save (DC 12) or be pushed 5ft and have their movement halved until the end of their turn.',
        cooldown: '2 turns',
      },
      {
        rank: 2,
        name: 'Shien Deflection',
        description: 'Apply Shien principles to redirect blaster bolts back at their source with surprising accuracy. When you deflect a blaster bolt, you may choose the direction of the deflection without a penalty to the attack roll.',
        cooldown: '1 reaction per turn',
      },
      {
        rank: 3,
        name: 'Fluid Riposte',
        description: 'Convert the energy of a blocked attack seamlessly into a powerful counter-strike. When you reduce damage with any defensive reaction, you may immediately make one melee attack as part of the same reaction.',
        cooldown: '1 reaction, 2 turns',
      },
      {
        rank: 4,
        name: 'Barrier of Blades',
        description: 'Create a near-impenetrable wall of spinning blade-work that intercepts projectiles automatically. Until the start of your next turn you automatically deflect the first two ranged attacks that target you.',
        cooldown: '3 turns',
      },
      {
        rank: 5,
        name: 'Falling Avalanche',
        description: 'Bring your blade down in a single earth-shaking overhead blow with your full might. Make one attack that deals triple your normal damage dice; if it hits, the target is knocked prone and stunned until end of their next turn.',
        cooldown: '3 turns',
      },
    ],
  },
  {
    name: 'Niman',
    title: 'Way of the Rancor / Moderation',
    ranks: [
      {
        rank: 1,
        name: 'Low Guard',
        description: 'Hold your blade in a low, deceptive guard that gives little away about your intentions. Enemies have disadvantage on checks to predict your attacks or read your combat style.',
        cooldown: 'N/A',
      },
      {
        rank: 2,
        name: 'Feint',
        description: 'Commit to a convincing false attack that draws your opponent\'s defense, then redirect to an opening. Make a Deception check contested by the target\'s Insight; on success your next attack against them has advantage.',
        cooldown: '2 turns',
      },
      {
        rank: 3,
        name: 'Draw Closer',
        description: 'Use a short telekinetic burst mid-combat to yank an enemy off-balance and into your blade\'s reach. Pull a target up to 10ft toward you as a bonus action, provoking no opportunity attacks.',
        cooldown: '2 turns',
      },
      {
        rank: 4,
        name: 'Pushing Slash',
        description: 'Combine a horizontal slash with a telekinetic shove to drive your opponent back. On a hit, the target takes normal damage and is pushed 10ft away from you.',
        cooldown: '2 turns',
      },
      {
        rank: 5,
        name: 'Falling Leaf',
        description: 'Flow seamlessly between saber strikes and Force techniques in the same sequence of actions, spending no additional action economy. Once per turn, using a Force ability does not consume your bonus action.',
        cooldown: '3 turns',
      },
    ],
  },
  {
    name: 'Juyo',
    title: 'Way of the Vornskr / Ferocity',
    ranks: [
      {
        rank: 1,
        name: 'Predatory Slash',
        description: 'Open with a savage strike intended to wound and intimidate. On a hit, deal an additional 1d4 damage and the target must make a Wisdom save (DC 11) or become shaken, suffering -1 to attack rolls until end of their next turn.',
        cooldown: '2 turns',
      },
      {
        rank: 2,
        name: 'Tempered Aggression',
        description: 'Channel your emotions into focused combat fury without losing control. While Tempered Aggression is active, you gain +1 to attack and damage rolls for each consecutive round you have been in melee combat (max +3).',
        cooldown: 'N/A',
      },
      {
        rank: 3,
        name: 'Swift Flank',
        description: 'Dart to your opponent\'s blind side in the blink of an eye, attacking from an angle they cannot defend. Move up to 10ft as part of an attack; if you end up adjacent to the target from a different direction, that attack has advantage.',
        cooldown: '2 turns',
      },
      {
        rank: 4,
        name: 'Assured Strike',
        description: 'Trust in your instincts and commit to a strike with total certainty. Once per turn you may reroll one failed attack roll and use the higher result.',
        cooldown: '2 turns',
      },
      {
        rank: 5,
        name: "Vornskr's Ferocity",
        description: "Unleash the full unbridled fury of Juyo. For the next minute, you make one additional attack whenever you take the Attack action, and your critical hit range expands to 19–20. Afterwards, you gain one level of exhaustion.",
        cooldown: '3 turns, once per Long Rest',
      },
    ],
  },
  {
    name: 'Trakata',
    title: 'Way of the Krykna / Deception',
    ranks: [
      {
        rank: 1,
        name: 'Off/On Parry',
        description: 'Momentarily deactivate your blade to let an enemy strike pass through, then reactivate and counter. When you use this reaction to dodge a melee attack, the attacker\'s momentum leaves them open and you gain advantage on your next attack against them.',
        cooldown: '1 reaction per turn',
      },
      {
        rank: 2,
        name: 'Sneaking Strike',
        description: 'Flick your blade off just before impact, disguising the killing blow as a miss, then reactivate at the last moment. This attack cannot be anticipated or blocked by predictive abilities and ignores the benefits of Force Sense.',
        cooldown: '2 turns',
      },
      {
        rank: 3,
        name: "Dead Man's Gamble",
        description: "Deactivate your blade and pretend to surrender or feign defeat, luring your opponent into a fatal overconfidence. Make a Deception check contested by Insight; on success you make one attack with advantage that deals an extra 2d6 damage.",
        cooldown: '3 turns',
      },
      {
        rank: 4,
        name: 'Deception Feint',
        description: 'Layer multiple convincing feints in rapid succession that create a cascade of false information for your opponent to process. The target must succeed on two Insight checks or be completely fooled, granting you advantage on all attacks against them for one round.',
        cooldown: '3 turns',
      },
      {
        rank: 5,
        name: "Krykna's Web",
        description: "Weave a complex web of feints, deactivations, and misdirections that leave your opponent completely unable to predict your next move. For 3 rounds, all your attacks have advantage, all attacks against you have disadvantage, and once per round you may make one additional attack as a free action.",
        cooldown: '3 turns, once per Long Rest',
      },
    ],
  },
]

export const nightSisterMagic: NightSisterSpell[] = [
  {
    name: 'Spectral Grasp',
    level: 1,
    description: 'Summon ghostly green ichor tendrils from the ground to seize and restrain a target. The target makes a Strength saving throw (DC 13) or is restrained for 1 turn.',
    range: '35ft',
    higherRank: 'Higher rank: restrain lasts 2 turns and/or DC increases to 15.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Ichor Bolt',
    level: 2,
    description: 'Conjure a bolt of crackling green Nightsister ichor and hurl it at a target. The target makes a Dexterity saving throw (DC 15) or takes 1d10 necrotic damage.',
    range: '40ft',
    higherRank: 'Higher rank: damage increases to 2d10.',
    cooldown: '2x per Long Rest',
  },
  {
    name: "Spirit's Touch",
    level: 3,
    description: "Channel the healing power of Dathomir's spirit ichor into a wounded creature, closing wounds and restoring vitality. The target regains 1d8 + Wisdom modifier hit points.",
    range: '20ft',
    higherRank: 'Higher rank: healing increases to 2d8 + Wisdom modifier.',
    cooldown: 'Long Rest',
  },
  {
    name: 'Blood Binding',
    level: 4,
    description: 'Forge a mystical ichor link between yourself and a target, tying your fates together. Any damage either of you receives is split equally between both parties for the duration. Target makes a Charisma save contested by your Wisdom.',
    range: '30ft',
    higherRank: 'N/A',
    cooldown: 'Long Rest',
  },
  {
    name: 'Ichor Ascension',
    level: 5,
    description: 'Suffuse yourself entirely with spirit ichor, ascending to a state of pure Nightsister power. You float above the ground, become resistant to physical damage, and all your other Nightsister spells may be cast as bonus actions for 3 turns.',
    range: 'Self',
    higherRank: 'N/A',
    cooldown: 'Long Rest',
  },
]
