import type { RaceData } from './types'

export const raceData: RaceData[] = [
  // ─── ORGANICS ───
  {
    name: 'Human',
    category: 'Organic',
    abilityScoreBonus: { dexterity: 1, intelligence: 1, charisma: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Pick one other'],
    abilities: [],
    equipment: [],
  },
  {
    name: 'Clone',
    category: 'Organic',
    abilityScoreBonus: { dexterity: 2, constitution: 1 },
    adulthood: '10 years old',
    lifeSpan: 'Half century',
    alignment: 'Usually Good',
    size: 'Medium',
    speed: 30,
    languages: ['Basic'],
    abilities: [],
    equipment: ['Plastoid Armor'],
  },
  {
    name: 'Mandalorian',
    category: 'Organic',
    abilityScoreBonus: { dexterity: 2, strength: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Neutral',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Mandalorian'],
    abilities: ['Proficiency in Melee Weapons'],
    equipment: ['Beskar Helmet'],
  },
  {
    name: 'Night Sister',
    category: 'Organic',
    abilityScoreBonus: { wisdom: 2 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Dathomirian'],
    abilities: ['Night Magic'],
    equipment: [],
  },
  {
    name: 'Zabrak',
    category: 'Organic',
    abilityScoreBonus: { strength: 1, dexterity: 1, intelligence: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Dathomirian'],
    abilities: [],
    equipment: [],
  },
  {
    name: "Twi'lek",
    category: 'Organic',
    abilityScoreBonus: { charisma: 2, dexterity: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Two centuries',
    alignment: 'N/A',
    size: 'Medium',
    speed: 35,
    languages: ['Basic', "Twi'leki"],
    abilities: ["Twi'lek Charm (Adv. on performance and persuasion checks)"],
    equipment: [],
  },
  {
    name: 'Togruta',
    category: 'Organic',
    abilityScoreBonus: { intelligence: 1, strength: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Good',
    size: 'Medium',
    speed: 35,
    languages: ['Basic', 'Togruti'],
    abilities: ['Echolocate (Feel vibrations of nearby creatures up to 25 ft)'],
    equipment: [],
  },
  {
    name: 'Chiss',
    category: 'Organic',
    abilityScoreBonus: { intelligence: 3 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Pick two others'],
    abilities: [],
    equipment: [],
  },
  {
    name: 'Chagrian',
    category: 'Organic',
    abilityScoreBonus: { strength: 2 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 25,
    languages: ['Basic', 'Pick one other'],
    abilities: ['Amphibious (can breathe normally both in and out of water)'],
    equipment: [],
  },
  {
    name: 'Cerean',
    category: 'Organic',
    abilityScoreBonus: { intelligence: 1, wisdom: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'More than a century',
    alignment: 'N/A',
    size: 'Large',
    speed: 30,
    languages: ['Basic'],
    abilities: ['Binary Brain (Adv. on investigation checks)'],
    equipment: [],
  },
  {
    name: 'Iktotchi',
    category: 'Organic',
    abilityScoreBonus: { strength: 2, constitution: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Iktotchese'],
    abilities: [],
    equipment: [],
  },
  {
    name: 'Utapaun',
    category: 'Organic',
    abilityScoreBonus: { intelligence: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Century and a half',
    alignment: 'N/A',
    size: 'Large',
    speed: 30,
    languages: ['Basic'],
    abilities: [],
    equipment: [],
  },
  {
    name: 'Umbaran',
    category: 'Organic',
    abilityScoreBonus: { charisma: 2, intelligence: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Umbaran'],
    abilities: ['Ultraviolet Vision (Can see ultraviolet light)'],
    equipment: [],
  },
  {
    name: 'Wookie',
    category: 'Organic',
    abilityScoreBonus: { strength: 2, constitution: 2 },
    adulthood: 'Early twenties',
    lifeSpan: '400 years',
    alignment: 'N/A',
    size: 'Large',
    speed: 25,
    languages: ['Shyriiwook'],
    abilities: ['Fur Coat (more comfortable in cold climates, less in deserts)'],
    equipment: [],
  },
  {
    name: 'Tuscan',
    category: 'Organic',
    abilityScoreBonus: { dexterity: 2, strength: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Neutral',
    size: 'Medium',
    speed: 30,
    languages: ['Tuscanese'],
    abilities: ['Desert Attuned (more comfortable in warm climates)'],
    equipment: [],
  },
  {
    name: 'Trandosian',
    category: 'Organic',
    abilityScoreBonus: { constitution: 2, strength: 1 },
    adulthood: 'Mid twenties',
    lifeSpan: 'Multiple centuries',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Dosh'],
    abilities: ['Reptilian Revival (Able to grow back lost limbs over multiple long rests)'],
    equipment: [],
  },
  {
    name: 'Gungan',
    category: 'Organic',
    abilityScoreBonus: { dexterity: 2 },
    adulthood: 'Early twenties',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Large',
    speed: 30,
    languages: ['Gunganese'],
    abilities: ['Amphibious', 'Leap (jump 15 ft high)'],
    equipment: [],
  },
  {
    name: 'Rodian',
    category: 'Organic',
    abilityScoreBonus: { constitution: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Rodian'],
    abilities: ['Infrared Vision (Can see Infrared Light)'],
    equipment: [],
  },
  {
    name: 'Nautolan',
    category: 'Organic',
    abilityScoreBonus: { dexterity: 1, intelligence: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Good',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Nautila (Uses Scent Speak)'],
    abilities: ['Amphibious', 'Scent Speak (Use pheromones to communicate)'],
    equipment: [],
  },
  {
    name: 'Bith',
    category: 'Organic',
    abilityScoreBonus: { intelligence: 2, charisma: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Bith'],
    abilities: ['Sensitive Hearing (advanced ears, sensitive to extremely loud noises)'],
    equipment: [],
  },
  {
    name: 'Sullustan',
    category: 'Organic',
    abilityScoreBonus: { dexterity: 1, intelligence: 1, wisdom: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 30,
    languages: ['Sullustese'],
    abilities: [],
    equipment: [],
  },
  {
    name: 'Clawdites',
    category: 'Organic',
    abilityScoreBonus: { charisma: 2 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Pick two others'],
    abilities: ['Chromatosis (take form of another humanoid at DM\'s permission)'],
    equipment: [],
  },
  {
    name: 'Mon Calamari',
    category: 'Organic',
    abilityScoreBonus: { intelligence: 2, dexterity: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Good',
    size: 'Medium',
    speed: 30,
    languages: ['Basic'],
    abilities: ['Amphibious'],
    equipment: [],
  },
  {
    name: 'Quarren',
    category: 'Organic',
    abilityScoreBonus: { strength: 1, wisdom: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Quarrenese'],
    abilities: ['Amphibious', 'Ink Spray (spray ink to temporarily blind a creature)'],
    equipment: [],
  },
  {
    name: 'Bothan',
    category: 'Organic',
    abilityScoreBonus: { strength: 1, dexterity: 1, charisma: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Large',
    speed: 35,
    languages: ['Basic', 'Pick one other'],
    abilities: [],
    equipment: [],
  },
  {
    name: 'Kel Dor',
    category: 'Organic',
    abilityScoreBonus: { constitution: 2, dexterity: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Kel Dorian'],
    abilities: [],
    equipment: [],
  },
  {
    name: 'Kaleesh',
    category: 'Organic',
    abilityScoreBonus: { dexterity: 2, strength: 1, constitution: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Kalee'],
    abilities: ['Na Jang (Adv. on hand to hand combat)'],
    equipment: [],
  },
  {
    name: 'Jawa',
    category: 'Organic',
    abilityScoreBonus: { intelligence: 1, charisma: 1 },
    adulthood: 'Mid teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Neutral',
    size: 'Small',
    speed: 20,
    languages: ['Jawaese'],
    abilities: [],
    equipment: ['Ion Blaster DC 14 (Stuns Droids)'],
  },
  {
    name: 'Ewok',
    category: 'Organic',
    abilityScoreBonus: { charisma: 2, dexterity: 1 },
    adulthood: 'Mid teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Small',
    speed: 20,
    languages: ['Ewokese'],
    abilities: ['Cute Charm (Adv. on attack before already engaged)'],
    equipment: [],
  },
  {
    name: 'Ugnaught',
    category: 'Organic',
    abilityScoreBonus: { intelligence: 2, wisdom: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Small',
    speed: 25,
    languages: ['Basic', 'Pick two others'],
    abilities: ['Hard Worker (finished tasks quicker, at DM\'s pace)'],
    equipment: [],
  },
  {
    name: 'Gamorrean',
    category: 'Organic',
    abilityScoreBonus: { strength: 2, constitution: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Evil',
    size: 'Large',
    speed: 30,
    languages: ['Basic', 'Pick one other'],
    abilities: ['Savage (Proficiency with large Melee Weapons)'],
    equipment: [],
  },
  {
    name: 'Ithorian',
    category: 'Organic',
    abilityScoreBonus: { constitution: 1, wisdom: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Good',
    size: 'Medium',
    speed: 30,
    languages: ['Ithorese'],
    abilities: [],
    equipment: ['Translator Collar (translates Ithorese to Basic)'],
  },
  {
    name: 'Ortolan',
    category: 'Organic',
    abilityScoreBonus: { charisma: 2, constitution: 1 },
    adulthood: 'Early teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Small',
    speed: 20,
    languages: ['Basic', 'Pick one other'],
    abilities: ['Blubber Skin (Not affected by frigid climates)'],
    equipment: [],
  },
  {
    name: 'Lasat',
    category: 'Organic',
    abilityScoreBonus: { strength: 2, dexterity: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'More than a century',
    alignment: 'Usually Good',
    size: 'Large',
    speed: 35,
    languages: ['Basic', 'Lasat'],
    abilities: ['Climber (Adv. on climbing)'],
    equipment: [],
  },
  {
    name: 'Yuzzum',
    category: 'Organic',
    abilityScoreBonus: { dexterity: 2 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 40,
    languages: ['Basic', 'Yuzzum'],
    abilities: [],
    equipment: [],
  },
  {
    name: 'Pyke',
    category: 'Organic',
    abilityScoreBonus: { intelligence: 2, wisdom: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Pyke', 'Pick one other'],
    abilities: ['Spice Supplier (Immune to the effects of Spice)'],
    equipment: [],
  },
  {
    name: 'Hutt',
    category: 'Organic',
    abilityScoreBonus: { constitution: 3 },
    adulthood: 'Less than a century',
    lifeSpan: '1000 years',
    alignment: 'N/A',
    size: 'Large',
    speed: 15,
    languages: ['Huttese'],
    abilities: ['Strong Minded (Immune to Mind Tricks)'],
    equipment: [],
  },
  {
    name: 'Toydarian',
    category: 'Organic',
    abilityScoreBonus: { intelligence: 2 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Pick one other'],
    abilities: ['Strong Minded', 'Flight (15 ft. high, 20 ft. fast)'],
    equipment: [],
  },
  {
    name: 'Besalisk',
    category: 'Organic',
    abilityScoreBonus: { dexterity: 1, constitution: 1 },
    adulthood: 'Late teens',
    lifeSpan: 'Less than a century',
    alignment: 'N/A',
    size: 'Large',
    speed: 25,
    languages: ['Basic', 'Pick one other'],
    abilities: ['Four Armed (can use up to four one-handed weapons, or two two-handed weapons)'],
    equipment: [],
  },

  // ─── DROIDS ───
  {
    name: 'B1',
    category: 'Droid',
    abilityScoreBonus: { dexterity: 1 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Binary', 'Droidspeak'],
    abilities: [],
    equipment: [],
  },
  {
    name: 'B2',
    category: 'Droid',
    abilityScoreBonus: { dexterity: 1, constitution: 1 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Droid Speak'],
    abilities: [],
    equipment: ['Wrist Blaster (1d6 50/100)'],
  },
  {
    name: 'BX',
    category: 'Droid',
    abilityScoreBonus: { dexterity: 3 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 35,
    languages: ['Basic', 'Droid Speak'],
    abilities: ['Nimble Joints (Adv. on Acrobatics Checks)'],
    equipment: [],
  },
  {
    name: 'Astromech',
    category: 'Droid',
    abilityScoreBonus: { constitution: 1, charisma: 1 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'N/A',
    size: 'Small',
    speed: 25,
    languages: ['Binary'],
    abilities: ['Based on model'],
    equipment: [],
  },
  {
    name: 'Protocol',
    category: 'Droid',
    abilityScoreBonus: { intelligence: 2 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'N/A',
    size: 'Medium',
    speed: 15,
    languages: ['All'],
    abilities: [],
    equipment: [],
  },
  {
    name: 'Tactical',
    category: 'Droid',
    abilityScoreBonus: { intelligence: 3 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Basic', 'Binary', 'Droidspeak'],
    abilities: ['Advanced Processor (Adv. on Perception checks)'],
    equipment: [],
  },
  {
    name: 'IG',
    category: 'Droid',
    abilityScoreBonus: { dexterity: 2, constitution: 1, intelligence: 1 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'Usually Evil',
    size: 'Large',
    speed: 30,
    languages: ['Basic', 'Binary', 'Droid Speak'],
    abilities: ['High Tech Sensors (Adv. on attacks from longer than 100 ft.)'],
    equipment: [],
  },
  {
    name: 'Magnaguard',
    category: 'Droid',
    abilityScoreBonus: { dexterity: 2, strength: 1 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'Usually Evil',
    size: 'Medium',
    speed: 30,
    languages: ['Droid Speak'],
    abilities: ['Savage (Proficiency with large Melee Weapons)'],
    equipment: [],
  },
  {
    name: 'Security',
    category: 'Droid',
    abilityScoreBonus: { strength: 2, constitution: 2 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'Usually Evil',
    size: 'Large',
    speed: 25,
    languages: ['Basic', 'Droid Speak'],
    abilities: ['Oppressive Stature (Adv. on Aura checks)'],
    equipment: [],
  },
  {
    name: 'Medical',
    category: 'Droid',
    abilityScoreBonus: { intelligence: 2, dexterity: 1 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'N/A',
    size: 'Medium',
    speed: 25,
    languages: ['Basic', 'Binary', 'Droid Speak'],
    abilities: ['Medical Database (Adv. on Medicine checks)'],
    equipment: [],
  },
  {
    name: 'Gonk',
    category: 'Droid',
    abilityScoreBonus: { charisma: 3 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'N/A',
    size: 'Small',
    speed: 20,
    languages: ['Binary'],
    abilities: ['Cute Charm (Adv. on attack before already engaged)'],
    equipment: [],
  },
  {
    name: 'Pit Droid',
    category: 'Droid',
    abilityScoreBonus: { dexterity: 2 },
    adulthood: 'N/A',
    lifeSpan: 'N/A',
    alignment: 'N/A',
    size: 'Small',
    speed: 25,
    languages: ['Binary', 'Droid Speak'],
    abilities: ['Turtle (+3 AC but immobile)'],
    equipment: [],
  },
]

export const organicRaces = raceData.filter((r) => r.category === 'Organic')
export const droidRaces = raceData.filter((r) => r.category === 'Droid')
