import type { Weapon, Shield, AdvancedWeapon } from './types';

export const weapons: Weapon[] = [
  // --- Lightsabers ---
  {
    name: 'Cracked Lightsaber',
    category: 'Lightsaber',
    cost: 'Priceless',
    damage: '1d8',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Throwable'],
  },
  {
    name: 'Lightsaber Pistol',
    category: 'Lightsaber',
    cost: 'Priceless',
    damage: '1d8',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Form Change: 1d4 Energy (30/50)'],
  },
  {
    name: 'Lightsaber',
    category: 'Lightsaber',
    cost: 'Priceless',
    damage: '2d8',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Throwable'],
  },
  {
    name: 'Proto Saber',
    category: 'Lightsaber',
    cost: 'Priceless',
    damage: '2d6',
    rangeOrType: 'Slashing/Piercing',
    attributes: [],
  },
  {
    name: 'Dual Blade Lightsaber',
    category: 'Lightsaber',
    cost: 'Priceless',
    damage: '2d8',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Two Handed'],
  },
  {
    name: 'Curved Hilt Lightsaber',
    category: 'Lightsaber',
    cost: 'Priceless',
    damage: '2d8',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Throwable'],
  },
  {
    name: 'Cross Guard Lightsaber',
    category: 'Lightsaber',
    cost: 'Priceless',
    damage: '2d8',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Hilt Attack: 1d4'],
  },
  {
    name: 'Lightsaber Pike',
    category: 'Lightsaber',
    cost: 'Priceless',
    damage: '2d8',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Two Handed'],
  },
  {
    name: 'Inquisitor Lightsaber',
    category: 'Lightsaber',
    cost: 'Priceless',
    damage: '2d8',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Throwable', 'Spinning'],
  },

  // --- Pistol Blasters ---
  {
    name: 'DH-17',
    category: 'Pistol Blaster',
    cost: '500',
    damage: '1d6',
    rangeOrType: '50/100',
    attributes: [],
  },
  {
    name: 'SE-14C',
    category: 'Pistol Blaster',
    cost: '400',
    damage: '1d6',
    rangeOrType: '30/70',
    attributes: [],
  },
  {
    name: 'Scout',
    category: 'Pistol Blaster',
    cost: '300',
    damage: '1d4',
    rangeOrType: '30/70',
    attributes: [],
  },
  {
    name: 'DL-18',
    category: 'Pistol Blaster',
    cost: '450',
    damage: '1d6',
    rangeOrType: '50/100',
    attributes: ["Droid's Bane"],
  },
  {
    name: 'DT-12',
    category: 'Pistol Blaster',
    cost: '375',
    damage: '1d4',
    rangeOrType: '30/70',
    attributes: [],
  },
  {
    name: 'Stinger',
    category: 'Pistol Blaster',
    cost: '800',
    damage: '1d6',
    rangeOrType: '50/100',
    attributes: [],
  },
  {
    name: 'K-16 Bryar',
    category: 'Pistol Blaster',
    cost: '900',
    damage: '1d6',
    rangeOrType: '30/70',
    attributes: [],
  },
  {
    name: 'A180',
    category: 'Pistol Blaster',
    cost: '900',
    damage: '1d4',
    rangeOrType: '50/100',
    attributes: [],
  },
  {
    name: 'DT-29',
    category: 'Pistol Blaster',
    cost: '700',
    damage: '1d4',
    rangeOrType: '30/70',
    attributes: [],
  },
  {
    name: 'DC-17',
    category: 'Pistol Blaster',
    cost: '1000',
    damage: '1d4',
    rangeOrType: '50/100',
    attributes: ["Droid's Bane"],
  },
  {
    name: 'RG-4D',
    category: 'Pistol Blaster',
    cost: '1200',
    damage: '1d6',
    rangeOrType: '70/130',
    attributes: [],
  },
  {
    name: 'RK-3',
    category: 'Pistol Blaster',
    cost: '550',
    damage: '1d4',
    rangeOrType: '30/50',
    attributes: [],
  },
  {
    name: 'Glie-44',
    category: 'Pistol Blaster',
    cost: '650',
    damage: '1d4',
    rangeOrType: '30/70',
    attributes: [],
  },
  {
    name: 'SE-44',
    category: 'Pistol Blaster',
    cost: '700',
    damage: '1d4',
    rangeOrType: '30/70',
    attributes: ["Droid's Bane"],
  },
  {
    name: 'Blurgg-1120',
    category: 'Pistol Blaster',
    cost: '500',
    damage: '1d4',
    rangeOrType: '30/50',
    attributes: ["Droid's Bane"],
  },

  // --- Rifle Blasters ---
  {
    name: 'E-11',
    category: 'Rifle Blaster',
    cost: '750',
    damage: '2d6',
    rangeOrType: '100/200',
    attributes: [],
  },
  {
    name: 'A280C',
    category: 'Rifle Blaster',
    cost: '1500',
    damage: '2d8',
    rangeOrType: '200/400',
    attributes: [],
  },
  {
    name: 'EE-4',
    category: 'Rifle Blaster',
    cost: '600',
    damage: '2d6',
    rangeOrType: '70/150',
    attributes: [],
  },
  {
    name: 'CJ-9 Bo-Rifle',
    category: 'Rifle Blaster',
    cost: '3500',
    damage: '2d6',
    rangeOrType: '70/150',
    attributes: ['Explosive 1d4 5ft radius'],
  },
  {
    name: 'DC-15A',
    category: 'Rifle Blaster',
    cost: '1750',
    damage: '2d8',
    rangeOrType: '70/150',
    attributes: ["Droid's Bane"],
  },
  {
    name: 'E-5',
    category: 'Rifle Blaster',
    cost: '450',
    damage: '2d6',
    rangeOrType: '100/200',
    attributes: [],
  },
  {
    name: 'EL-16',
    category: 'Rifle Blaster',
    cost: '700',
    damage: '2d6',
    rangeOrType: '70/150',
    attributes: [],
  },
  {
    name: 'F-11D',
    category: 'Rifle Blaster',
    cost: '1500',
    damage: '2d6',
    rangeOrType: '100/200',
    attributes: [],
  },
  {
    name: 'A280',
    category: 'Rifle Blaster',
    cost: '1800',
    damage: '2d8',
    rangeOrType: '200/400',
    attributes: ["Droid's Bane"],
  },
  {
    name: 'CR-2',
    category: 'Rifle Blaster',
    cost: '1200',
    damage: '2d6',
    rangeOrType: '70/150',
    attributes: ["Droid's Bane"],
  },
  {
    name: 'EL-16HFE',
    category: 'Rifle Blaster',
    cost: '1900',
    damage: '2d8',
    rangeOrType: '100/200',
    attributes: ["Droid's Bane"],
  },
  {
    name: 'E-11D',
    category: 'Rifle Blaster',
    cost: '2200',
    damage: '2d8',
    rangeOrType: '200/400',
    attributes: [],
  },

  // --- Heavy Blasters ---
  {
    name: 'DLT-19',
    category: 'Heavy Blaster',
    cost: '1200',
    damage: '2d10',
    rangeOrType: '50/100',
    attributes: [],
  },
  {
    name: 'RT-97C',
    category: 'Heavy Blaster',
    cost: '1100',
    damage: '2d10',
    rangeOrType: '70/130',
    attributes: [],
  },
  {
    name: 'T-21',
    category: 'Heavy Blaster',
    cost: '1500',
    damage: '1d4',
    rangeOrType: '70/130',
    attributes: ['Multi Hit: 5'],
  },
  {
    name: 'TL-50 Heavy Repeater',
    category: 'Heavy Blaster',
    cost: '3500',
    damage: '1d4',
    rangeOrType: '50/100',
    attributes: ['Multi Hit: 6', "Droid's Bane"],
  },
  {
    name: 'DC-15',
    category: 'Heavy Blaster',
    cost: '2000',
    damage: '2d10',
    rangeOrType: '50/100',
    attributes: ["Droid's Bane"],
  },
  {
    name: 'FWMB-10',
    category: 'Heavy Blaster',
    cost: '3000',
    damage: '1d4',
    rangeOrType: '30/70',
    attributes: ['Multi Hit: 8'],
  },
  {
    name: 'DC-15LE',
    category: 'Heavy Blaster',
    cost: '2500',
    damage: '2d10',
    rangeOrType: '70/130',
    attributes: ["Droid's Bane"],
  },
  {
    name: 'FWMB-10K',
    category: 'Heavy Blaster',
    cost: '4000',
    damage: '1d4',
    rangeOrType: '30/70',
    attributes: ['Multi Hit: 8', "Droid's Bane"],
  },
  {
    name: 'TL-50',
    category: 'Heavy Blaster',
    cost: '2750',
    damage: '1d4',
    rangeOrType: '70/130',
    attributes: ['Multi Hit: 5'],
  },
  {
    name: 'T-21A',
    category: 'Heavy Blaster',
    cost: '3250',
    damage: '1d4',
    rangeOrType: '50/100',
    attributes: ['Multi Hit: 6'],
  },

  // --- Sniper Blasters ---
  {
    name: 'Valken-38X',
    category: 'Sniper Blaster',
    cost: '4500',
    damage: '3d10',
    rangeOrType: '600/100',
    attributes: ["Droid's Bane"],
  },
  {
    name: 'E-5S',
    category: 'Sniper Blaster',
    cost: '3000',
    damage: '4d6',
    rangeOrType: '500/100',
    attributes: [],
  },
  {
    name: 'DLT-20A',
    category: 'Sniper Blaster',
    cost: '3400',
    damage: '4d6',
    rangeOrType: '500/100',
    attributes: [],
  },
  {
    name: 'A180',
    category: 'Sniper Blaster',
    cost: '3500',
    damage: '2d10',
    rangeOrType: '600/100',
    attributes: [],
  },
  {
    name: 'IQA-11',
    category: 'Sniper Blaster',
    cost: '4250',
    damage: '4d8',
    rangeOrType: '800/100',
    attributes: ["Droid's Bane", 'Collapseable'],
  },
  {
    name: 'NT-242',
    category: 'Sniper Blaster',
    cost: '4000',
    damage: '4d8',
    rangeOrType: '800/100',
    attributes: [],
  },
  {
    name: 'Cycler Rifle',
    category: 'Sniper Blaster',
    cost: '3000',
    damage: '3d6',
    rangeOrType: '500/100',
    attributes: [],
  },
  {
    name: 'DLT-19D',
    category: 'Sniper Blaster',
    cost: '5000',
    damage: '3d10',
    rangeOrType: '600/100',
    attributes: ['Smart Targeting'],
  },
  {
    name: 'T-21B',
    category: 'Sniper Blaster',
    cost: '3750',
    damage: '4d6',
    rangeOrType: '300/70',
    attributes: ['Smart Targeting'],
  },
  {
    name: 'DLT-19X',
    category: 'Sniper Blaster',
    cost: '4275',
    damage: '4d8',
    rangeOrType: '600/70',
    attributes: ['Smart Targeting'],
  },
  {
    name: 'Relby-V10',
    category: 'Sniper Blaster',
    cost: '4900',
    damage: '3d10',
    rangeOrType: '400/70',
    attributes: ['Smart Targeting'],
  },

  // --- Melee Weapons ---
  {
    name: 'Knife',
    category: 'Melee',
    cost: '100',
    damage: '1d4',
    rangeOrType: 'Slashing/Piercing',
    attributes: [],
  },
  {
    name: 'Vibro-Knife',
    category: 'Melee',
    cost: '400',
    damage: '1d4',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Causes Bleed'],
  },
  {
    name: 'Vibro-Sword',
    category: 'Melee',
    cost: '800',
    damage: '1d6',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Causes Bleed'],
  },
  {
    name: 'Vibro-Axe',
    category: 'Melee',
    cost: '1000',
    damage: '1d6',
    rangeOrType: 'Slashing',
    attributes: ['Causes Bleed'],
  },
  {
    name: 'Vibro-Lance',
    category: 'Melee',
    cost: '1500',
    damage: '1d8',
    rangeOrType: 'Piercing',
    attributes: ['Causes Bleed'],
  },
  {
    name: 'Vibro-Staff',
    category: 'Melee',
    cost: '1500',
    damage: '1d8',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Causes Bleed'],
  },
  {
    name: 'Vibro-Knuckler',
    category: 'Melee',
    cost: '700',
    damage: '1d4',
    rangeOrType: 'Bludgeoning',
    attributes: ['Causes Bleed'],
  },
  {
    name: 'Electro Gauntlets',
    category: 'Melee',
    cost: '800',
    damage: '1d6',
    rangeOrType: 'Bludgeoning',
    attributes: ['Electric: 1d4'],
  },
  {
    name: 'Resonator Mace',
    category: 'Melee',
    cost: '3000',
    damage: '1d8',
    rangeOrType: 'Electric',
    attributes: ['Causes Stun'],
  },
  {
    name: 'Gaderffii Stick',
    category: 'Melee',
    cost: '400',
    damage: '1d6',
    rangeOrType: 'Bludgeoning',
    attributes: [],
  },
  {
    name: 'Vamblade',
    category: 'Melee',
    cost: '500',
    damage: '1d6',
    rangeOrType: 'Slashing/Piercing',
    attributes: ['Retractable'],
  },
  {
    name: 'KX Club',
    category: 'Melee',
    cost: '300',
    damage: '1d4',
    rangeOrType: 'Bludgeoning',
    attributes: [],
  },
  {
    name: "Champion's Club",
    category: 'Melee',
    cost: '500',
    damage: '1d6',
    rangeOrType: 'Bludgeoning',
    attributes: [],
  },
  {
    name: 'Electrostaff',
    category: 'Melee',
    cost: '2000',
    damage: '1d8',
    rangeOrType: 'Bludgeoning',
    attributes: ['Electric: 1d4'],
  },
  {
    name: 'Tranquilizer Harpoon',
    category: 'Melee',
    cost: '1000',
    damage: '1d6',
    rangeOrType: 'Piercing',
    attributes: ['Causes Sleep'],
  },
  {
    name: 'Zhaboka',
    category: 'Melee',
    cost: '700',
    damage: '1d8',
    rangeOrType: 'Slashing/Piercing',
    attributes: [],
  },
  {
    name: 'Spear',
    category: 'Melee',
    cost: '500',
    damage: '1d8',
    rangeOrType: 'Piercing',
    attributes: [],
  },
  {
    name: 'Battle Axe',
    category: 'Melee',
    cost: '600',
    damage: '1d8',
    rangeOrType: 'Slashing',
    attributes: [],
  },
  {
    name: 'Slicewire',
    category: 'Melee',
    cost: '400',
    damage: '1d4',
    rangeOrType: 'Slashing',
    attributes: ['Sneak Attack: 1d12'],
  },
  {
    name: 'Fear Stick',
    category: 'Melee',
    cost: '1500',
    damage: '1d4',
    rangeOrType: 'Piercing',
    attributes: ['Causes Frightened and Confusion'],
  },
  {
    name: 'Tomahawk',
    category: 'Melee',
    cost: '100',
    damage: '1d6',
    rangeOrType: 'Slashing',
    attributes: ['Throwable'],
  },
  {
    name: 'Throwing Knives',
    category: 'Melee',
    cost: '50',
    damage: '1d4',
    rangeOrType: 'Piercing',
    attributes: ['Throwable'],
  },
  {
    name: 'Chakram',
    category: 'Melee',
    cost: '200',
    damage: '1d6',
    rangeOrType: 'Slashing',
    attributes: ['Throwable'],
  },

  // --- Nomadic Weapons ---
  {
    name: 'Long Bow',
    category: 'Nomadic',
    cost: '300',
    damage: '1d8',
    rangeOrType: 'Piercing (150/600)',
    attributes: ['Projectile Variety'],
  },
  {
    name: 'Short Bow',
    category: 'Nomadic',
    cost: '200',
    damage: '1d6',
    rangeOrType: 'Piercing (100/400)',
    attributes: ['Projectile Variety'],
  },
  {
    name: 'Sling',
    category: 'Nomadic',
    cost: '50',
    damage: '1d6',
    rangeOrType: 'Bludgeoning (50/100)',
    attributes: ['Difficult'],
  },
  {
    name: 'Slingshot',
    category: 'Nomadic',
    cost: '50',
    damage: '1d4',
    rangeOrType: 'Bludgeoning (25/50)',
    attributes: [],
  },
  {
    name: 'Blow Gun',
    category: 'Nomadic',
    cost: '150',
    damage: '1d4',
    rangeOrType: 'Piercing (25/50)',
    attributes: ['Projectile Variety'],
  },
  {
    name: 'Net Gun',
    category: 'Nomadic',
    cost: '900',
    damage: '1d6',
    rangeOrType: 'Range 20',
    attributes: ['Projectile Variety', 'Traps all in 5 ft radius'],
  },
  {
    name: 'Bola',
    category: 'Nomadic',
    cost: '150',
    damage: '1d4',
    rangeOrType: 'Bludgeoning (25/50)',
    attributes: ['Traps Target'],
  },
];

export const shields: Shield[] = [
  {
    name: 'Grafted',
    cost: '400',
    acBonus: 1,
    against: ['Pistol Blaster', 'Rifle Blaster', 'Melee', 'Nomadic'],
    attributes: ['Bash 1d4 Bludgeoning'],
  },
  {
    name: 'Plastoid',
    cost: '600',
    acBonus: 2,
    against: ['Pistol Blaster', 'Rifle Blaster', 'Melee', 'Nomadic'],
    attributes: ['Bash 1d4 Bludgeoning'],
  },
  {
    name: 'Gungan',
    cost: '400',
    acBonus: 1,
    against: ['Pistol Blaster', 'Rifle Blaster', 'Heavy Blaster', 'Sniper Blaster'],
    attributes: [],
  },
  {
    name: 'Plasma',
    cost: '600',
    acBonus: 2,
    against: ['Pistol Blaster', 'Rifle Blaster', 'Heavy Blaster', 'Sniper Blaster'],
    attributes: [],
  },
  {
    name: 'Bounceback',
    cost: '3000',
    acBonus: 1,
    against: ['Pistol Blaster', 'Rifle Blaster', 'Heavy Blaster', 'Sniper Blaster'],
    attributes: ['Deflect'],
  },
  {
    name: 'Wooden',
    cost: '200',
    acBonus: 1,
    against: ['Melee', 'Nomadic'],
    attributes: ['Bash 1d4 Bludgeoning'],
  },
  {
    name: 'Beskar',
    cost: '5000',
    acBonus: 3,
    against: ['Lightsaber', 'Pistol Blaster', 'Rifle Blaster', 'Heavy Blaster', 'Sniper Blaster', 'Melee', 'Nomadic'],
    attributes: ['Bash 1d4 Bludgeoning'],
  },
];

export const advancedWeapons: AdvancedWeapon[] = [
  {
    name: 'Thermal Detonator',
    price: '2000',
    description: 'A compact, spherical explosive that detonates with devastating force in a wide radius.',
    range: '15 ft radius',
    damage: '3d8 explosive',
    worn: 'N/A',
  },
  {
    name: 'Sticky Thermal Detonator',
    price: '2500',
    description: 'A thermal detonator coated in adhesive that sticks to any surface or target before detonating.',
    range: '15 ft radius',
    damage: '3d8 explosive',
    worn: 'N/A',
  },
  {
    name: 'EMP Grenade',
    price: '750',
    description: 'Releases a burst of electromagnetic energy that disables droids and electronic systems in the area.',
    range: '15 ft radius',
    damage: 'N/A',
    worn: 'N/A',
  },
  {
    name: 'Concussion Grenade',
    price: '3500',
    description: 'A high-yield explosive grenade that produces a powerful concussive shockwave on detonation.',
    range: '10 ft radius',
    damage: '4d8 explosive',
    worn: 'N/A',
  },
  {
    name: 'Adhesive Grenade',
    price: '600',
    description: 'Disperses a fast-hardening adhesive foam that immobilizes targets caught in the blast zone.',
    range: '20 ft radius',
    damage: 'N/A',
    worn: 'N/A',
  },
  {
    name: 'Proton Grenade',
    price: 'Your left kidney per half grenade',
    description: 'An extraordinarily rare and catastrophically powerful explosive. Handle — if you can afford one — with extreme care.',
    range: '30 ft radius',
    damage: '4d10 explosive',
    worn: 'N/A',
  },
  {
    name: 'Flash Grenade',
    price: '750',
    description: 'Emits a blinding flash of light on detonation, temporarily disorienting and blinding targets in range.',
    range: '15 ft radius',
    damage: 'N/A',
    worn: 'N/A',
  },
  {
    name: 'Bacta Bomb',
    price: '1500',
    description: 'Disperses a mist of bacta on detonation, healing allies caught in the radius.',
    range: '15 ft radius',
    damage: 'Heals 1d8',
    worn: 'N/A',
  },
  {
    name: 'Shockwave Grenade',
    price: '1000',
    description: 'Generates a focused force shockwave that knocks back and damages targets in the blast area.',
    range: '10 ft radius',
    damage: '1d4 force',
    worn: 'N/A',
  },
  {
    name: 'Inferno Grenade',
    price: '2000',
    description: 'Releases a cloud of incendiary material that ignites on contact, leaving targets burning each turn.',
    range: '15 ft radius',
    damage: '1d8 burning/turn',
    worn: 'N/A',
  },
  {
    name: 'Gas Grenade',
    price: '1700',
    description: 'Disperses a toxic gas cloud that poisons targets who breathe it in, dealing ongoing damage each turn.',
    range: '15 ft radius',
    damage: '1d8 poison/turn',
    worn: 'N/A',
  },
  {
    name: 'Smoke Bomb',
    price: '500',
    description: 'Releases a thick cloud of smoke that obscures vision and provides concealment for those inside.',
    range: '20 ft radius',
    damage: 'N/A',
    worn: 'N/A',
  },
  {
    name: 'Noise Grenade',
    price: '300',
    description: 'Emits a loud, disorienting burst of sound across a wide area, useful for creating diversions.',
    range: '40 ft radius',
    damage: 'N/A',
    worn: 'N/A',
  },
  {
    name: 'Whipcord Launcher',
    price: '9000',
    description: 'A wrist-mounted launcher that fires a strong cord to entangle and restrain targets at range.',
    range: '30 ft',
    damage: 'N/A',
    worn: 'Wrist',
  },
  {
    name: 'Flamethrower',
    price: '12000',
    description: 'A forearm-mounted flamethrower that projects a cone of burning fuel, incinerating targets ahead.',
    range: '25 ft',
    damage: '2d12 burning',
    worn: 'Forearm',
  },
  {
    name: 'Wrist Laser',
    price: '15000',
    description: 'A compact but powerful laser emitter strapped to the wrist, capable of firing concentrated energy bolts.',
    range: '40 ft',
    damage: '5d6 piercing',
    worn: 'Wrist',
  },
  {
    name: 'Concussion Rocket',
    price: '9000',
    description: 'A wrist-launched micro-rocket that detonates with concussive force on impact.',
    range: '30 ft, 5 ft radius',
    damage: '2d10 explosive',
    worn: 'Wrist',
  },
  {
    name: 'Ascension Cables',
    price: '6000',
    description: 'Wrist-mounted grappling cables used to scale walls, cross gaps, or reach elevated positions quickly.',
    range: '30 ft',
    damage: 'N/A',
    worn: 'Wrist',
  },
  {
    name: 'Jetpack Missile',
    price: '20000',
    description: 'A guided missile launched from a back-mounted jetpack system, delivering a massive explosive payload.',
    range: '45 ft, 10 ft radius',
    damage: '4d8 explosive',
    worn: 'Back',
  },
  {
    name: 'HDM',
    price: '7500',
    description: 'A chest-mounted heavy defense module that provides additional protection and tactical countermeasures.',
    range: 'N/A',
    damage: 'N/A',
    worn: 'Chest',
  },
  {
    name: 'Rocket Darts',
    price: '4000',
    description: 'Knee-mounted micro-rockets that fire small explosive darts at nearby targets.',
    range: '20 ft',
    damage: '1d6 per dart',
    worn: 'Knee',
  },
  {
    name: 'Whistling Birds',
    price: '20000',
    description: 'Forearm-launched tracking micro-darts that home in on multiple targets simultaneously.',
    range: '20 ft',
    damage: '1d8 per dart',
    worn: 'Forearm',
  },
  {
    name: 'Magnetic Boots',
    price: '3000',
    description: 'Boots with electromagnetic soles that allow the wearer to walk on metal surfaces in zero-gravity environments.',
    range: 'N/A',
    damage: 'N/A',
    worn: 'Feet',
  },
  {
    name: 'Buzzsaw Glove',
    price: '4000',
    description: 'A gauntlet fitted with a high-speed rotating blade, effective for cutting through materials and close-quarters combat.',
    range: 'Self',
    damage: '2d8',
    worn: 'Hand',
  },
  {
    name: 'Shield Gauntlet',
    price: '14000',
    description: 'A forearm-mounted energy shield projector that can be activated to block incoming attacks.',
    range: 'Self',
    damage: 'N/A',
    worn: 'Forearm',
  },
  {
    name: 'Sidewinder',
    price: '6500',
    description: 'A shoulder-mounted launcher that fires a fast-moving, curved trajectory projectile at targets.',
    range: '30 ft',
    damage: '4d6',
    worn: 'Shoulder',
  },
  {
    name: 'Mechanical Arm',
    price: '17500',
    description: 'A powerful cybernetic back-mounted mechanical arm that augments physical capability and reach.',
    range: 'N/A',
    damage: 'N/A',
    worn: 'Back',
  },
];
